module.exports = {
  add: require('./add'),
  tagall: require('./tagall'),
  kick: require('./kick'),
  menfess: require('./menfess'),
  welcome: require('./welcome'),
  tiktokDownloader: require('./tiktokDownloader'),
  igDownloader: require('./igDownloader'),
  youtubeDownloader: require('./youtubeDownloader'),
  sendAll: require('./sendAll'),
  show: require('./show'),
  qris: require('./qris'),
  createQr: require('./createQr'),
  mapqr: require('./mapqr'),
  linkmap: require('./linkmap'),
  waifuhen: require('./waifuhen'),
  waifu: require('./waifu'),
  stickerToMedia: require('./stickerToMedia'),
  admin: require('./admin'),
  translate: require('./translate')
}
